# Author       : Xuemin Zhao <xmzhao1986@gmail.com>
# Created Time : 2013-03-24
# Description  :

cc_library(
  name = "glog",
  srcs = [
    "demangle.cc",
    "logging.cc",
    "raw_logging.cc",
    "signalhandler.cc",
    "symbolize.cc",
    "utilities.cc",
    "vlog_is_on.cc",
  ],
  incs = '.',
  deps = [
    '#pthread',
  ],
  warning = 'no'
)
